Update CI.yml

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -17,22 +17,34 @@ jobs:
         run: |
           cd ./flowers/flowers
           scheme_list=$(xcodebuild -list -json | tr -d "\n")
-          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
-          echo "$default" > default
-          echo "Using default scheme: $default"
+          default_scheme=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
+          echo "$default_scheme" > default_scheme.txt
+          echo "Using default scheme: $default_scheme"
       - name: Test
-        env:
-          scheme: ${{ env.default }}
-          platform: 'iOS Simulator'
         run: |
           cd ./flowers/flowers
           device=$(xcrun xctrace list devices 2>&1 | grep -oE 'iPhone.*?[^\(]+' | head -1 | awk '{$1=$1;print}' | sed -e "s/ Simulator$//")
           echo "Using device: $device"
+          if [ -f "default_scheme.txt" ]; then
+            scheme=$(cat default_scheme.txt)
+          else
+            echo "Error: Default scheme file not found."
+            exit 1
+          fi
           if [ -z "$scheme" ]; then
             echo "Error: No scheme provided."
             exit 1
           fi
-          xcodebuild test -scheme "$scheme" -destination "platform=$platform,name=$device" -enableCodeCoverage YES || true
+          if [ "$(ls -A | grep -i \\.xcworkspace\$)" ]; then
+            filetype_parameter="workspace"
+            file_to_build="$(ls -A | grep -i \\.xcworkspace\$)"
+          else
+            filetype_parameter="project"
+            file_to_build="$(ls -A | grep -i \\.xcodeproj\$)"
+          fi
+          file_to_build=$(echo "$file_to_build" | awk '{$1=$1;print}')
+          echo "File to build: $file_to_build"
+          xcodebuild test -scheme "$scheme" -"$filetype_parameter" "$file_to_build" -destination "platform=iOS Simulator,name=$device" -enableCodeCoverage YES || true
 
   build:
     runs-on: macos-12
@@ -45,19 +57,31 @@ jobs:
         run: |
           cd ./flowers/flowers
           scheme_list=$(xcodebuild -list -json | tr -d "\n")
-          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
-          echo "$default" > default
-          echo "Using default scheme: $default"
+          default_scheme=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
+          echo "$default_scheme" > default_scheme.txt
+          echo "Using default scheme: $default_scheme"
       - name: Build
-        env:
-          scheme: ${{ env.default }}
-          platform: 'iOS Simulator'
         run: |
           cd ./flowers/flowers
           device=$(xcrun xctrace list devices 2>&1 | grep -oE 'iPhone.*?[^\(]+' | head -1 | awk '{$1=$1;print}' | sed -e "s/ Simulator$//")
           echo "Using device: $device"
+          if [ -f "default_scheme.txt" ]; then
+            scheme=$(cat default_scheme.txt)
+          else
+            echo "Error: Default scheme file not found."
+            exit 1
+          fi
           if [ -z "$scheme" ]; then
             echo "Error: No scheme provided."
             exit 1
           fi
-          xcodebuild build -scheme "$scheme" -destination "platform=$platform,name=$device" || true
+          if [ "$(ls -A | grep -i \\.xcworkspace\$)" ]; then
+            filetype_parameter="workspace"
+            file_to_build="$(ls -A | grep -i \\.xcworkspace\$)"
+          else
+            filetype_parameter="project"
+            file_to_build="$(ls -A | grep -i \\.xcodeproj\$)"
+          fi
+          file_to_build=$(echo "$file_to_build" | awk '{$1=$1;print}')
+          echo "File to build: $file_to_build"
+          xcodebuild build -scheme "$scheme" -"$filetype_parameter" "$file_to_build" -destination "platform=iOS Simulator,name=$device" || true
